backend:
  name: github
  repo: Nocteln/portfolio_v3
  branch: master # Note: vérifiez si votre branche principale s'appelle bien "main", sinon changez en "master"
  # Proxy OAuth interne fait maison :
  base_url: https://nocteln.fr
  auth_endpoint: oauth/auth

# C'est ici que les images téléchargées dans l'éditeur vont être stockées (commitées).
media_folder: "public/img/writeups"
public_folder: "/img/writeups"

# Activation du mode "Brouillon"
publish_mode: editorial_workflow

# Définition de la collection d'articles
collections:
  - name: "writeups"
    label: "Write-Ups CTF"
    folder: "content/writeups"
    create: true
    # Le nom du fichier sera formaté automatiquement
    slug: "{{year}}-{{month}}-{{title}}"
    fields:
      - {label: "Brouillon (Caché au public)", name: "draft", widget: "boolean", default: false}
      - {label: "Titre du challenge", name: "title", widget: "string"}
      - {label: "Nom du CTF (Optionnel)", name: "ctf", widget: "string", required: false}
      - {label: "Plateforme", name: "platform", widget: "select", options: ["HackTheBox", "TryHackMe", "RootMe", "Autre"], default: "HackTheBox"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Image / Vignette", name: "image", widget: "image", required: false}
      - {label: "Description (Optionnelle)", name: "description", widget: "string", required: false}
      - {label: "Contenu / Article (Markdown)", name: "body", widget: "markdown"}
